def cky():
    """
    The CKY algorithm finds all possible parses of an ambiguous sentence or phrase generated by a CFG.
    """
    pass


def pcky():
    """
    Ney's variant of the CKY algorithm finds a most probable parse for a phrase or sentence
    in the language generated by an ambiguous Probabilistic Context-Free Grammar.
    """
    pass
